FROM mhart/alpine-node:13

WORKDIR /app/nextjs

COPY package.json package.json

COPY next.config.js next.config.js
COPY webpackOverrides.js webpackOverrides.js
COPY dist dist/

RUN yarn --frozen-lockfile
RUN yarn build

EXPOSE 3000

ENTRYPOINT ["node", "dist/nextjs.cjs.js"]