name: Publish Docker
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish 'tundera-base' to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: johnstonpt/tundera-base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 'tundera-nextjs' to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: johnstonpt/tundera-nextjs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 'tundera-website' to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: johnstonpt/tundera-website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
